### ISSUE TITLE
Missing dataset file

### ISSUE THREAD

**Issue by koenvervloesem** [DreamerMind/snips-app-onboarding#1]
Hi Julien,

I just tried to run your app, but I get this exception:

```
Apr 29 08:48:39 snips snips-skill-server[22199]: INFO:snips_skill_server_lib::runner            : [onboard][err] Traceback (most recent call last):                
Apr 29 08:48:39 snips snips-skill-server[22199]: INFO:snips_skill_server_lib::runner            : [onboard][err]   File "./action-onboard.py", line 144, in <module>                                                                          
Apr 29 08:48:39 snips snips-skill-server[22199]: INFO:snips_skill_server_lib::runner            : [onboard][err]     OnBoardingApp()
Apr 29 08:48:39 snips snips-skill-server[22199]: INFO:snips_skill_server_lib::runner            : [onboard][err]   File "./action-onboard.py", line 41, in __init__   
Apr 29 08:48:39 snips snips-skill-server[22199]: INFO:snips_skill_server_lib::runner            : [onboard][err]     for _ in self._assistant.dataset.intent_per_name.keys()   
Apr 29 08:48:39 snips snips-skill-server[22199]: INFO:snips_skill_server_lib::runner            : [onboard][err]   File "/var/lib/snips/skills/snips-app-onboarding/venv/lib/python3.5/site-packages/snips_app_helpers/snips/assistant.py", li
ne 107, in dataset                                                                                                                            
Apr 29 08:48:39 snips snips-skill-server[22199]: INFO:snips_skill_server_lib::runner            : [onboard][err]     self.language, self._original_path.parent / "dataset.json"
Apr 29 08:48:39 snips snips-skill-server[22199]: INFO:snips_skill_server_lib::runner            : [onboard][err]   File "/var/lib/snips/skills/snips-app-onboarding/venv/lib/python3.5/site-packages/snips_app_helpers/snips/dataset/__init__.
py", line 176, in from_json                                                                                                                                                               
Apr 29 08:48:39 snips snips-skill-server[22199]: INFO:snips_skill_server_lib::runner            : [onboard][err]     raise ValueError('Missing dataset file @ %s' % str(filepath))
Apr 29 08:48:39 snips snips-skill-server[22199]: INFO:snips_skill_server_lib::runner            : [onboard][err] ValueError: Missing dataset file @ /usr/share/snips/assistant/dataset.json
Apr 29 08:48:39 snips snips-skill-server[22199]: WARN:snips_skill_server_lib::handler::nosandbox: child onboard has stopped with status `exit code: 1`     
Apr 29 08:48:39 snips snips-skill-server[22199]: INFO:snips_skill_server_lib::runner            : restarting action onboard (restart_fails: 2)  
```

Are you trying to load the Snips NLU dataset that has been used to train the assistant? As far as I know, that file is not in the `/usr/share/snips/assistant` directory. At least not when I deploy assistants from the Snips Console.

**Comment by DreamerMind** [comment]
Hi koen,
Not sure what is your assistant install procedure.
I am using sam to deploy the assistant (tested on the pi for now only with default config). 
Just tested:
- `rm -rf /usr/share/snips/assistant`
- `sam assistant install`
- `ls -lah /usr/share/snips/assistant` (show dataset.json)
Do you have a different behaviour ? (it should be the same with tar.gz extraction since `dataset.json` is in it)

**Comment by koenvervloesem** [comment]
I just added your app to my assistant in Snips Console and did `sam install assistant` on Raspbian.

I'll try again later today.

**Comment by DreamerMind** [comment]
I am on raspbian too, might it be a permission problem ?
`-rw-r--r-- 1 pi pi 929K Apr 29 12:10 /usr/share/snips/assistant/dataset.json`

Thanks for your interest in the app.

**Comment by koenvervloesem** [comment]
I really don't have this file in my assistant:

```
pi@snips:~ $ ls -lah /usr/share/snips/assistant
total 44K
drwxr-xr-x 6 pi   pi   4.0K Apr 29 18:25 .
drwxr-xr-x 9 root root 4.0K Apr 29 18:25 ..
-rw-r--r-- 1 pi   pi    11K Apr 29 16:25 assistant.json
drwxr-xr-x 3 pi   pi   4.0K Apr 29 18:25 custom_asr
drwxr-xr-x 4 pi   pi   4.0K Apr 29 18:25 custom_dialogue
drwxr-xr-x 7 pi   pi   4.0K Apr 29 18:25 nlu_engine
drwxr-xr-x 9 pi   pi   4.0K Apr 29 18:25 snippets
-rw-r--r-- 1 pi   pi    755 Apr 29 16:25 Snipsfile.yaml
-rw-r--r-- 1 pi   pi     26 Apr 29 16:25 trained_assistant.json
```

I never had this file in any of my assistants. Otherwise, I would have discovered it and I would have written your onboarding app myself some time ago ;-)

I wiped my assistant directory and did `sam install assistant`, but the only files I see are the ones above. I also downloaded the zip file manually and inspected it, and the result is the same: no `dataset.json`.

I even created an assistant from scratch in Snips Console, added your app to it and deployed it. The result is the same.

This is with Snips Flow 1.1.2 (0.62.3) on Raspbian 9.8.

**Comment by DreamerMind** [comment]
Maybe a difference since I am console admin ...
I will ask today.
Sorry for the inconveniance (I wasn't aware of that if that if that's the case) 

thanks for the feedback.

**Comment by DreamerMind** [comment]
Discussed with our CTO today,
Sadly this `dataset.json` is only shipped with admin account and is not planned to be accessible for now from console...

While I hope this `feature blockage` will be removed with time, I have received no encouraging sign (it is locked in part because some of the user pay for dataset augmentation while willing to ship their assistant in production env without data to avoid assistant replication + keeping consistant the 'unforkable' setting in console app + few other reasons ).

I am really disapointed to say that this app will not serve anyone except internal snipsters ....
Will update the readme to reflect that.
